"""Provider package for AI Shorts Studio.

Contains provider interfaces and implementations for LLM, image, and video
generation. Providers are kept separate from the agent layer so the agents
are not coupled to any specific vendor.
"""

from backend.providers.base import (
    AsyncJob,
    AsyncJobStatus,
    AsyncImageProvider,
    AsyncVideoProvider,
    AsyncPollingClient,
    GenerationOptions,
    GenerationStatus,
    GenerationResult,
    ImageGenerationResult,
    VideoGenerationResult,
    ProviderCapabilities,
    ProviderCapabilityError,
    ProviderError,
    ProviderNotConfiguredError,
    ProviderTimeoutError,
    ProviderRemoteError,
    ProviderValidationError,
    ProviderAuthError,
    ProviderInvalidRequestError,
    ProviderQuotaError,
    ProviderRateLimitError,
    ProviderQuotaExceededError,
    ProviderSafetyError,
    ProviderUnavailableError,
    ProviderGenerationError,
    CAP_TEXT_TO_IMAGE,
    CAP_MULTI_CANDIDATE,
    CAP_ASYNC,
)

__all__ = [
    "AsyncJob",
    "AsyncJobStatus",
    "AsyncImageProvider",
    "AsyncVideoProvider",
    "AsyncPollingClient",
    "GenerationOptions",
    "GenerationStatus",
    "GenerationResult",
    "ImageGenerationResult",
    "VideoGenerationResult",
    "ProviderCapabilities",
    "ProviderCapabilityError",
    "ProviderError",
    "ProviderNotConfiguredError",
    "ProviderTimeoutError",
    "ProviderRemoteError",
    "ProviderValidationError",
    "ProviderAuthError",
    "ProviderInvalidRequestError",
    "ProviderQuotaError",
    "ProviderRateLimitError",
    "ProviderQuotaExceededError",
    "ProviderSafetyError",
    "ProviderUnavailableError",
    "ProviderGenerationError",
    "CAP_TEXT_TO_IMAGE",
    "CAP_MULTI_CANDIDATE",
    "CAP_ASYNC",
]
